//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public int ProductQuantity { get; set; }
        public Nullable<System.Guid> StockId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StocksInfo StocksInfo { get; set; }
    }
}
